-- Outboxy Inbox Pattern - Table Definitions
-- MySQL DDL for inbox_events table
--
-- Usage:
--   mysql -u user -p database < 003_create_inbox_tables.sql
--   mysql -u user -p database < 004_create_inbox_indexes.sql
--
-- Or run with previous migrations:
--   cat sql/mysql/*.sql | mysql -u user -p database

-- =============================================================================
-- inbox_events: Transactional inbox for idempotent event consumption
-- =============================================================================
-- Purpose: Provide idempotent processing via deduplication of received events by tracking
-- which events have already been handled via idempotency keys.
--
-- Unlike outbox_events, inbox_events has no worker - the consumer's
-- transaction is the integration layer. Insert happens atomically with
-- business logic in the same transaction.
CREATE TABLE IF NOT EXISTS `inbox_events` (
    -- Primary identifier (MySQL uses CHAR(36) for UUIDs)
    -- Pre-generated by SDK since MySQL doesn't support gen_random_uuid()
    `id` CHAR(36) NOT NULL PRIMARY KEY,

    -- Idempotency key (REQUIRED - this is the whole point of inbox)
    -- Consumer chooses what constitutes uniqueness:
    -- - Transport-level: kafka:orders:0:12345 (partition + offset)
    -- - Business-level: order-abc123-created
    -- - Hybrid: payment-svc:charge-xyz789
    `idempotency_key` VARCHAR(255) NOT NULL,

    -- Source (optional, for observability)
    -- Tracks where the event came from (e.g., "webhook", "kafka:orders", "stripe")
    `source` VARCHAR(255),

    -- Event metadata (consistent with outbox_events)
    `aggregate_type` VARCHAR(255) NOT NULL,
    `aggregate_id` VARCHAR(255) NOT NULL,
    `event_type` VARCHAR(255) NOT NULL,
    `event_version` INT DEFAULT 1 NOT NULL,

    -- Payload (MySQL JSON type)
    `payload` JSON NOT NULL,
    `headers` JSON DEFAULT (JSON_OBJECT()),
    `metadata` JSON DEFAULT (JSON_OBJECT()),

    -- Status (simpler than outbox - only 2 states)
    -- 'processed' = event was handled successfully
    -- 'failed' = business logic failed, needs attention (but NOT retried automatically)
    `status` ENUM('processed', 'failed') NOT NULL DEFAULT 'processed',
    `error` TEXT,

    -- Timestamps
    `received_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `processed_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Unique constraint on idempotency_key
    UNIQUE KEY `idx_inbox_idempotency` (`idempotency_key`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
