global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "outboxy-worker"
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
